export const projects = {
    android: [{
            title: 'Covid-19 Tracker',
            description: "COVID-19 Tracker is a free, open-source Android application that shows the current state of COVID-19 in Nigeria. It has a beautiful, simple, fast, and responsive UI.",
            image: '/images/covid.PNG',
            tags: ['Java', 'XML', 'Dark Theme', 'WHO'],
            source: 'https://github.com/TuleSimon/covid-19',
            youtube: 'https://www.youtube.com/watch?v=d_b7zWIRNh8&t=45s',
            visit: 'https://drive.google.com/file/d/14aEbcVu9fiBE1Hj4YuXZV948zuUWNnX4/view?usp=sharing',
            id: 0,
        },
        {
            title: 'FUOLIB',
            description: "Fuo Library Management System, a project i built for my Final Year Project Exams.",
            image: '/images/fuolib.PNG',
            tags: ['Kotlin', 'Firebase'],
            source: 'https://github.com/TuleSimon/FuoLibraryManagementSystem2',
            visit: 'https://drive.google.com/file/d/1jZGs4P8-UjsOeAbG8PZIL2aGj6KBky1x/view?usp=sharing',
            id: 1,
        },
        {
            title: 'SChat',
            description: "A social Media Real time Chat Application with Profile Features, Image Uploading, Online Status and many other features",
            image: '/images/soniachat.PNG',
            tags: ['Kotlin', 'Firebase', 'Dark Theme', 'Lottie'],
            source: 'https://github.com/TuleSimon/SChat',
            visit: 'https://drive.google.com/file/d/1oDiWViuGI3kKdonCGGUMBowiNZKrIBX0/view?usp=sharing',
            id: 3,
        },
    ],
    Java: [{
            title: 'CTRACK',
            description: "A Crime Management System developed using Java, Javafx, FontAwesome, JFeonix, SQllite and Firebase",
            image: '/images/ctrack.jpeg',
            tags: ['Java', 'Javafx', 'FXML', 'Sqllite', 'Firebase', 'FontAwesome', 'JFeonix'],
            source: '',
            visit: 'https://drive.google.com/file/d/1rDFbXBizxlmZOcV0FPCBd80aI9HS35mR/view?usp=sharing',
            id: 0,
            disabled: true,
        },
        {
            title: 'JAVA LIB',
            description: "Java Library Management System, a project i built to be the Desktop version of my Mobile FUOLIB.",
            image: '/images/javafxlib.PNG',
            tags: ['Java', 'Javafx', 'FXML', 'Sqllite', 'FontAwesome', 'JFeonix'],
            source: 'https://github.com/TuleSimon/Javafx-LibraryManagement-System',
            youtube: 'https://www.youtube.com/watch?v=79dFkkTlz6w',
            id: 1,
            disabled: true,
        },
    ],
    web: [{
            title: 'T&Gee Exchange',
            description: "A Bitcoin Trader Profile Landing Page i Built Using ReactJs and Material UI",
            image: '/images/t&g.png',
            tags: ['React', 'Css', 'Html', 'Material UI', 'EmailJS'],
            source: 'https://github.com/TuleSimon/TGeeXchange',
            visit: 'https://tg-xchange.web.app/',
            id: 0,

        },
        {
            title: 'XBroker',
            description: "A bitcoin broker Site i built as a training Project using React Js .",
            image: '/images/xbroker.PNG',
            tags: ['React', 'Firebase', 'Antd', 'Material UI', 'Redux', 'Lottie'],
            disabled: 'true',
            visit: 'https://xdevbroker.web.app/',
            id: 1,
            disabled: true,
        },
        {
            title: 'XBlog',
            description: "A Personal Blog i built using GraphCMS for myself to post dynamic content, as well as keep in touch with my users.",
            image: '/images/blog.png',
            tags: ['React', 'NextJS', 'Material Icons', 'Redux', 'Tailwind', 'GraphCMS'],
            source: 'https://github.com/TuleSimon/XBlog',
            visit: 'https://xblog-tulesimon.vercel.app/',
            id: 1,

        },
    ],

};

export const TimeLineData = [
    { year: 2016, text: 'Started my journey as a new developer.', },
    { year: 2017, text: 'Worked intensively on ROMs & Kernels.', },
    { year: 2018, text: 'Learned Android app development.', },
    { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
    { year: 2020, text: 'Got a scholarship from the Delhi government.', },
    { year: 2021, text: 'Still trying to figure out this weird year.', },
];